#########################################################
#                                                       #
#                       SCRIPT                          #
#                                                       #
#########################################################
shell_command:
  smarther_update: ver=$(curl -ksL "https://api.github.com/repos/danye72/smarther-v1/releases" | jq -r "map(select(.draft==false)) | first" | jq -r ".tag_name") && curl -s "https://raw.githubusercontent.com/danye72/smarther-v1/$ver/script/update" | bash -s

script:
  update_from_smarther_github_repo:
    alias: Update smarther integration from GitHub repository
    sequence:
      - service: shell_command.smarther_update
      - service: homeassistant.update_entity
        entity_id: sensor.smarther_current_release, sensor.smarther_latest_release, binary_sensor.smarther_updater

  smarther_release_sensors_update:
    alias: Update smarther release sensors manually
    sequence:
      - service: homeassistant.update_entity
        entity_id: sensor.smarther_current_release, sensor.smarther_latest_release, binary_sensor.smarther_updater

#########################################################
#                                                       #
#                        SENSOR                         #
#                                                       #
#########################################################
sensor:
  - platform: command_line
    name: "Smarther current release"
    command: cat /config/smarther/.smarther_version
    scan_interval: 10800
    value_template: "{{ value_json.tag_name }}"
    json_attributes:
      - "html_url"
      - "name"
      - "draft"
      - "prerelease"
      - "published_at"
      - "body"

  - platform: command_line
    name: "Smarther latest release"
    command: curl --silent "https://api.github.com/repos/danye72/smarther-v1/releases" | jq -r "map(select(.draft==false)) | first"
    scan_interval: 3600
    value_template: "{{ value_json.tag_name }}"
    json_attributes:
      - "html_url"
      - "name"
      - "draft"
      - "prerelease"
      - "published_at"
      - "body"

#########################################################
#                                                       #
#                    BINARY SENSOR                      #
#                                                       #
#########################################################
binary_sensor:
  - platform: template
    sensors:
      smarther_updater:
        friendly_name: "Smarther updater"
        value_template: "{{ states('sensor.smarther_current_release') < states('sensor.smarther_latest_release') }}"
        device_class: update
        attribute_templates:
          current_version: "{{ states('sensor.smarther_current_release') }}"
          latest_version: "{{ states('sensor.smarther_latest_release') }}"
