version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - "${PWD}/homeassistant:/config"
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - "DISABLE_JEMALLOC:true"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - "${PWD}/mosquitto/config:/mosquitto/config"
      - "${PWD}/mosquitto/log:/mosquitto/log"
      - "${PWD}/mosquitto/data/:/mosquitto/data"
    restart: unless-stopped
    ports:
      - 1883:1883

  portainer:
    container_name: "portainer"
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - "admin-password:blablabla"