binary_sensor:
- platform: mqtt
  name: "SLS Gateway"
  state_topic: "ZigbeeF390/bridge/state"
  payload_on: "online"
  payload_off: "offline"
  device_class: "connectivity"

sensor:
# SLS Gateway Info
- platform: mqtt
  name: "sls_gateway_ip"
  state_topic: "ZigbeeF390/bridge/config"
  availability_topic: "ZigbeeF390/bridge/state"
  payload_available: "online"
  payload_not_available: "offline"
  icon: mdi:ip-network
  value_template: "{{ value_json.IP }}"

- platform: mqtt
  name: "sls_gateway_fw_ver"
  state_topic: "ZigbeeF390/bridge/config"
  availability_topic: "ZigbeeF390/bridge/state"
  payload_available: "online"
  payload_not_available: "offline"
  value_template: "{{ value_json.Version }}"

# Tracker info via SLS Gateway
- platform: mqtt
  name: "tracker_mobile_mario_ping"
  state_topic: "tracker/mobile_mario/info"
  icon: mdi:check-network
  value_template: "{{ value_json.ping | round() }}"
  unit_of_measurement: "ms"

- platform: mqtt
  name: "tracker_mobile_mario_ip"
  state_topic: "tracker/mobile_mario/info"
  icon: mdi:ip-network
  value_template: "{{ value_json.ip }}"

- platform: mqtt
  name: "tracker_mobile_mario_device"
  state_topic: "tracker/mobile_mario/info"
  icon: mdi:ip-network
  value_template: "{{ value_json.device }}"

- platform: mqtt
  name: "tracker_mobile_mario_attempt"
  state_topic: "tracker/mobile_mario/info"
  icon: mdi:counter
  value_template: "{{ value_json.attempt }}"
  unit_of_measurement: "retry/min"

- platform: mqtt
  name: "tracker_mobile_mario_fails"
  state_topic: "tracker/mobile_mario/info"
  icon: mdi:message-alert
  value_template: "{{ value_json.fails }}"
  unit_of_measurement: "ping fails"

- platform: mqtt
  name: "tracker_mobile_maria_ping"
  state_topic: "tracker/mobile_maria/info"
  icon: mdi:check-network
  value_template: "{{ value_json.ping | round() }}"
  unit_of_measurement: "ms"

- platform: mqtt
  name: "tracker_mobile_maria_ip"
  state_topic: "tracker/mobile_maria/info"
  icon: mdi:ip-network
  value_template: "{{ value_json.ip }}"

- platform: mqtt
  name: "tracker_mobile_maria_device"
  state_topic: "tracker/mobile_maria/info"
  icon: mdi:ip-network
  value_template: "{{ value_json.device }}"

- platform: mqtt
  name: "tracker_mobile_maria_attempt"
  state_topic: "tracker/mobile_maria/info"
  icon: mdi:counter
  value_template: "{{ value_json.attempt }}"
  unit_of_measurement: "retry/min"

- platform: mqtt
  name: "tracker_mobile_maria_fails"
  state_topic: "tracker/mobile_maria/info"
  icon: mdi:message-alert
  value_template: "{{ value_json.fails }}"
  unit_of_measurement: "ping fails"

automation:
- alias: SLS Gateway Online
  trigger:
  - entity_id: binary_sensor.sls_gateway
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: SLS Gateway Offline
      title: SLS Gateway ALERT!
    service: script.invia_notifica