##https://community.home-assistant.io/t/random-rgb-color-in-scene/32945/35

##########################################################################################
# Package Partymode light efetcs
##########################################################################################

homeassistant:
  customize:

    switch.mode_party:
      templates:
        icon: >
          if (state === 'on') return 'mdi:cake-layered';
          return 'mdi:hotel';
        icon_color: >
          if (state === 'on') return 'rgb(251, 210, 41)';
          return 'rgb(54, 95, 140)';

##########################################################################################
# Switch
##########################################################################################

switch:
  - platform: template
    switches:
      mode_party:
        friendly_name: Party mode switch
        value_template: >
          {{ is_state('automation.lights_partying', 'on') }}
        turn_on:
          # - service: script.home_mode_party #(turn off motion sensors, package home_mode)
          - service: script.lights_mode_party_on #(turn off sense lights automation, on party Lights
        turn_off:
          - service: script.lights_mode_party_off

  - platform: template
    switches:
      mode_christmas:
        friendly_name: Christmas mode switch
        value_template: >
          {{ is_state('automation.lights_christmas', 'on') }}
        turn_on:
          - service: script.lights_mode_christmas_on #(turn off sense lights automation, on party Lights
        turn_off:
          - service: script.lights_mode_christmas_off

##########################################################################################
# Scripts
##########################################################################################

script:

  lights_mode_party_on:
    alias: Party on
    sequence:
      # - service: homeassistant.turn_off
      #   entity_id: automation.sense_lights_change
      # - delay:
      #     seconds: 5
      - service: homeassistant.turn_on
        entity_id: automation.lights_partying

  lights_mode_party_off:
    alias: Party off
    sequence:
      - service: automation.turn_off
        entity_id: automation.lights_partying
      - delay: 
          seconds: 2
      - service: script.lights_partying_reset
      - delay: 
          seconds: 2
      - service: script.lights_partying_off
      # - delay:
      #     seconds: 10
      # - service: homeassistant.turn_on
      #   entity_id: automation.sense_lights_change

  lights_mode_christmas_on:
    alias: Christmas on
    sequence:
      # - service: homeassistant.turn_off
      #   entity_id: automation.sense_lights_change
      # - delay:
      #     seconds: 5
      - service: homeassistant.turn_on
        entity_id: automation.lights_christmas

  lights_mode_christmas_off:
    alias: Christmas off
    sequence:
      - service: automation.turn_off
        entity_id: automation.lights_christmas
      - delay: 
          seconds: 2
      - service: script.lights_partying_reset
      - delay: 
          seconds: 2
      - service: script.lights_partying_off
      # - delay:
      #     seconds: 10
      # - service: homeassistant.turn_on
      #   entity_id: automation.sense_lights_change

  lights_partying_on:
    alias: Lights partying on
    sequence:
      service: light.turn_on
      data_template:
        # entity_id: light.{{['dining_corner','cabinet','kist','home_theater']|random}}
        entity_id: light.bf0f6143383255aa5fzzja
        rgb_color: ['{{ (range(0, 255)|random) }}',
                    '{{ (range(0, 255)|random) }}',
                    '{{ (range(0, 255)|random) }}']
        brightness: '{{ (range(50, 250)|random) }}'
        transition: '{{ (range(1, 3)|random) }}'

  lights_christmas_on:
    alias: Christmas partying on
    sequence:
    - service: light.turn_on
      data_template:
        entity_id: light.bf0f6143383255aa5fzzja
        brightness: 255
        # color_name: 'white'
        rgb_color: ['255',
                    '255',
                    '255']
        transition: '{{ (range(1, 3)|random) }}'
    - delay: 
          seconds: 4
    - service: light.turn_on
      data_template:
        entity_id: light.bf0f6143383255aa5fzzja
        brightness: 255
        color_name: 'red'
        transition: '{{ (range(1, 3)|random) }}'

  lights_partying_reset:
    alias: Lights partying reset
    sequence:
      service: light.turn_on
      data:
        entity_id:
          - light.bf0f6143383255aa5fzzja
        #   - light.dining_corner
        #   - light.cabinet
        #   - light.kist
        #   - light.home_theater
        profile: relax

  lights_partying_off:
    alias: Lights partying off
    sequence:
      service: light.turn_off
      entity_id: 
          - light.bf0f6143383255aa5fzzja
        #   - light.dining_corner
        #   - light.cabinet
        #   - light.kist
        #   - light.home_theater

##########################################################################################
# Automations
##########################################################################################

automation:
  - id: 'lights_christmas'
    alias: Lights Christmas
    initial_state: 'off'
    trigger:
      platform: time_pattern
      seconds: '/4'   # {{ "/" ~ ((range(2, 5) | random) | int) }}
    # condition:
    #   condition: template
    #   value_template: >
    #     {{is_state('automation.sense_lights_change','off') }}
    action: 
      service: script.lights_christmas_on

  - id: 'lights_partying'
    alias: Lights partying
    initial_state: 'off'
    trigger:
      platform: time_pattern
      seconds: '/4'   # {{ "/" ~ ((range(2, 5) | random) | int) }}
    # condition:
    #   condition: template
    #   value_template: >
    #     {{is_state('automation.sense_lights_change','off') }}
    action: 
      service: script.lights_partying_on