#########################################################
#                                                       #
#                        X8000                          #
#                                                       #
#########################################################

homeassistant:
  customize:
    # package.node_anchors:
    #   customize: &customize
    #     package: 'termo_btc X8000'
    #     version: '1.0'
    #     author: 'Ducatista80'
    #     reference: 'DomoLife'
        
    #   expose: &expose
    #     <<: *customize
    #     haaska_hidden: false
    #     homebridge_hidden: false
    #     alexa: false
    #     google: false
        
        
    ##--------------------- IMPOSTAZIONI DEL PACKAGE ---------------------##
      setting:
        topic stato termostato: &topic_status '/bticino/6c663d9f-46fd-c20f-e053-1e182d0aa61c/status'
        topic comando termostato: &topic_cmd '/bticino/6c663d9f-46fd-c20f-e053-1e182d0aa61c/cmd'
        #deprecato rest_command, al riavvio, la card si aggiornera in automatico dopo qualche minuto. Se volete, potete comunque metterlo
        #al di fuori del package.
    ##--------------------------------------------------------------------##


#########################################################
#                                                       #
#                        SENSOR                         #
#                                                       #
#########################################################
sensor:

  #### SENSOR MQTT ####
  
    ### nome
  - platform: mqtt
    name: termo_btc_name
    state_topic: *topic_status
    value_template: '{{ value_json.name }}'

    ### temperatura
  - platform: mqtt
    name: termo_btc_temperatura
    state_topic: *topic_status
    value_template: '{{ value_json.temperature }}'
    
    ### umidità
  - platform: mqtt
    name: termo_btc_umidita
    state_topic: *topic_status
    value_template: '{{ value_json.humidity|int }}'

    ### funzione
  - platform: mqtt
    name: termo_btc_funzione
    state_topic: *topic_status
    value_template: "{{ value_json.function }}"

    ### mode
  - platform: mqtt
    name: termo_btc_mode
    state_topic: *topic_status
    value_template: "{{ value_json.mode }}"

    ### set point
  - platform: mqtt
    name: termo_btc_set_point
    state_topic: *topic_status
    value_template: "{{ value_json.setpoint|round (1) }}"

    ### stato
  - platform: mqtt
    name: termo_btc_stato
    state_topic: *topic_status
    value_template: "{{ value_json.state }}"

    ### programma
  - platform: mqtt
    name: termo_btc_programma
    state_topic: *topic_status
    value_template: "{{ value_json.state|float|int }}"


  #### SENSOR TEMPLATE ####
  - platform: template
    sensors:

      ### Switch visualizzazione Temp Sp Umid
      termo_btc_switch_visual_int:
        value_template: >
            {% if is_state('input_number.termo_btc_set_boost', '0.0') %}
              {% if is_state('input_boolean.termo_btc_change_temp', 'on') or is_state('input_number.termo_btc_switch_visual', '1.0') %}
                {{ states('input_number.termo_btc_set_sp')|int }}
              {% elif is_state('input_number.termo_btc_switch_visual', '0.0') %}
                {{ states('sensor.termo_btc_temperatura')|int }}
              {% elif is_state('input_number.termo_btc_switch_visual', '2.0') %}
                {{ states('sensor.termo_btc_umidita') }}
              {% endif %}
            {% elif is_state('input_number.termo_btc_set_boost', '30.0') %}30
            {% elif is_state('input_number.termo_btc_set_boost', '60.0') %}60
            {% elif is_state('input_number.termo_btc_set_boost', '90.0') %}90
            {% endif %}

      ### Switch decimale visualizzazione Temperatura Setpoint
      termo_btc_switch_visual_dec:
        value_template: >
            {% set value_temp = states('sensor.termo_btc_temperatura')|float %}
            {% set intero_temp = states('sensor.termo_btc_temperatura')|int %}
            {% set decimale_temp = ((value_temp - intero_temp) * 10)|round(0) %}
            {% set value_sp = states('input_number.termo_btc_set_sp')|float %}
            {% set intero_sp = states('input_number.termo_btc_set_sp')|int %}
            {% set decimale_sp = ((value_sp - intero_sp) * 10)|round(0) %}
            {% if is_state('input_number.termo_btc_set_boost', '0.0') %}
              {% if is_state('input_boolean.termo_btc_change_temp', 'on') or is_state('input_number.termo_btc_switch_visual', '1.0') %}
                {{ decimale_sp }}
              {% elif is_state('input_number.termo_btc_switch_visual', '0.0') %}
                {{ decimale_temp }}
              {% elif is_state('input_number.termo_btc_switch_visual', '2.0') %}
              {% endif %}
            {% endif %}

      ### Visualizza Gradi o Percentuale o Minuti
      termo_btc_switch_um:
        value_template: >
            {% if is_state('input_number.termo_btc_set_boost', '0.0') %}
              {% if is_state('input_number.termo_btc_switch_visual', '0.0') %}°
              {% elif is_state('input_number.termo_btc_switch_visual', '1.0')%}°
              {% elif is_state('input_number.termo_btc_switch_visual', '2.0')%}%
              {% endif %}
            {% endif %}

      ### Switch minuti boost
      termo_btc_switch_min:
        value_template: >
            {% if is_state('input_boolean.termo_btc_change_temp', 'on') or
                  is_state('input_number.termo_btc_switch_visual', '1.0')%}SET
            {% elif is_state('input_number.termo_btc_set_boost', '0.0') %}
            {% elif is_state('input_number.termo_btc_set_boost', '30.0') %}MIN
            {% elif is_state('input_number.termo_btc_set_boost', '60.0') %}MIN
            {% elif is_state('input_number.termo_btc_set_boost', '90.0') %}MIN
            {% endif %}
                
########################################################


#########################################################
#                                                       #
#                    BINARY SENSOR                      #
#                                                       #
#########################################################

binary_sensor:

  - platform: template
    sensors:
    
    ### stato relè del termostato
      termo_btc_stato_custom:
        value_template: >-
            {{ is_state('sensor.termo_btc_stato', 'ACTIVE') }}
        icon_template: >-
            {% set funzione = states('sensor.termo_btc_funzione') %}
            {% if funzione == 'HEATING' %}mdi:fire
            {% elif funzione == 'COOLING' %}mdi:snowflake
            {% endif %}
        device_class: power

    ### stato funzionamento off o protection
      termo_btc_spento:
        value_template: "{{ is_state('sensor.termo_btc_mode', 'PROTECTION') or is_state('sensor.termo_btc_mode', 'OFF') }}"
        icon_template: mdi:power
        device_class: power

    ### stato funzionamento in automatico
      termo_btc_auto:
        value_template: "{{ is_state('sensor.termo_btc_mode', 'AUTOMATIC') }}"
        icon_template: mdi:autorenew
        device_class: power

    ### stato funzionamento in manuale
      termo_btc_man:
        value_template: "{{ is_state('sensor.termo_btc_mode', 'MANUAL') }}"
        icon_template: mdi:hand-right
        device_class: power

    ### stato funzionamento in boost
      termo_btc_boost:
        value_template: "{{ is_state('sensor.termo_btc_mode', 'BOOST') }}"
        icon_template: mdi:play-speed
        device_class: power

  ########################################


#########################################################
#                                                       #
#                        INPUT                          #
#                                                       #
#########################################################

  #### INPUT BOOLEAN ####
input_boolean:
  termo_btc_change_temp:
    initial: 'off'
    
  termo_btc_change_boost:
    initial: 'off'


  #### INPUT NUMBER ####
input_number:

  termo_btc_set_sp:
    min: 7
    max: 30
    step: 0.5

  termo_btc_set_boost:
    initial: 0
    min: 0
    max: 120
    step: 30

  termo_btc_switch_visual:
    initial: 0
    min: 0
    max: 3
    step: 1 

#########################################################



#########################################################
#                                                       #
#                      AUTOMATION                       #
#                                                       #
#########################################################

automation:

  ##########################
  #### RICHIAMO COMANDI ####
  ##########################
  
  #### COMANDO SET POINT ####
  - id: 'termo_btc set point temperatura cambiata'
    alias: termo_btc Invia Set Point Temperatura Termostato
    trigger:
      platform: state
      entity_id: input_boolean.termo_btc_change_temp
      to: 'on'
      for: '00:00:10'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.termo_btc_cmd_setpoint

  #### COMANDO BOOST ####
  - id: 'termo_btc richiama script comando boost'
    alias: termo_btc Richiama Script comando boost
    trigger:
      platform: state
      entity_id: input_boolean.termo_btc_change_boost
      to: 'on'
      for: '00:00:10'
    action:
      - service: script.turn_on
        entity_id: script.termo_btc_cmd_boost

  ######################################

  ##############################
  #### AUTOMAZIONI PER CARD ####
  ##############################

  #### AZZERAMENTO SET BOOST ####
  - id: 'termo_btc azzera boost'
    alias: termo_btc Azzera Boost
    trigger:
      - platform: numeric_state
        entity_id: input_number.termo_btc_set_boost
        above: '90.0'
    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_set_boost
          value: "0.0"

  #### AZZERAMENTO SWITCH VISUAL ####
  - id: 'termo_btc azzera switch visual'
    alias: termo_btc Azzera Switch Visualizzazione
    trigger:
      - platform: numeric_state
        entity_id: input_number.termo_btc_switch_visual
        above: '2.0'
      - platform: numeric_state
        entity_id: input_number.termo_btc_switch_visual
        above: '0.0'
        for: '00:00:10'
    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_switch_visual
          value: "0.0"

  #### AZZERARE VALORI DOPO AVER PREMUTO BOOST ####
  - id: 'termo_btc azzera vari input'
    alias: termo_btc Azzera vari input dopo aver premuto il boost
    trigger:
      platform: state
      entity_id: input_number.termo_btc_set_boost
    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_switch_visual
          value: "0.0"
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.termo_btc_change_temp

  #### RICEVE SET POINT TEMPERATURA ####
  - id: 'termo_btc ricevi set point temperatura'
    alias: termo_btc Riceve Set Point Temperatura Termostato
    trigger:
      platform: state
      entity_id: sensor.termo_btc_set_point
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.termo_btc_set_sp
          value: "{{states('sensor.termo_btc_set_point')}}"


########################################################



#########################################################
#                                                       #
#                        SCRIPT                         #
#                                                       #
#########################################################

script:

  #### INVIO COMANDO SET POINT ####
  termo_btc_cmd_setpoint:
    sequence:
      - condition: state
        entity_id: input_number.termo_btc_set_boost
        state: '0.0'
      - condition: state
        entity_id: input_boolean.termo_btc_change_boost
        state: 'off'
      - service: mqtt.publish
        data_template:
          topic: *topic_cmd
          payload: >-
                {% set my_test_json = {"temperature": states.input_number.termo_btc_set_sp.state} %}
                {{my_test_json.temperature}}
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.termo_btc_change_temp
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_switch_visual
          value: "0.0"

  
  #### INVIO COMANDO AUTO ####       
  termo_btc_cmd_auto:
    sequence:
      - condition: state
        entity_id: input_number.termo_btc_set_boost
        state: '0.0'
      - condition: state
        entity_id: binary_sensor.termo_btc_auto
        state: 'off'
      - service: mqtt.publish
        data_template:
          topic: *topic_cmd
          payload: AUTOMATIC
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_set_boost
          value: "0.0"
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.termo_btc_change_boost
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_switch_visual
          value: "0.0"


  #### INVIO COMANDO MANUALE ####       
  termo_btc_cmd_man:
    sequence:
      - condition: state
        entity_id: input_number.termo_btc_set_boost
        state: '0.0'
      - condition: state
        entity_id: binary_sensor.termo_btc_man
        state: 'off'
      - service: mqtt.publish
        data_template:
          topic: *topic_cmd
          payload: MANUAL
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_set_boost
          value: "0.0"
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_switch_visual
          value: "0.0"

  
  #### INVIO COMANDO PROTECTION #### 
  termo_btc_cmd_off:
    sequence:
      - condition: state
        entity_id: input_number.termo_btc_set_boost
        state: '0.0'
      - condition: state
        entity_id: binary_sensor.termo_btc_spento
        state: 'off'
      - service: mqtt.publish
        data_template:
          topic: *topic_cmd
          payload: PROTECTION
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_set_boost
          value: "0.0"
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.termo_btc_change_boost
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_switch_visual
          value: "0.0"


  #### INVIO COMANDO BOOST ####
  termo_btc_cmd_boost:
    sequence:
      - wait_template: "{% if states('input_number.termo_btc_set_boost') != '0.0' %} true {%else%} false {%endif%}"
        timeout: '00:00:01'
        continue_on_timeout: 'false'
      - service: mqtt.publish
        data_template:
          topic: *topic_cmd
          payload: >-
                {% set my_test_json = {"boost": states.input_number.termo_btc_set_boost.state|int} %}
                BOOST-{{my_test_json.boost}}
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_set_boost
          value: "0.0"
      - service: input_number.set_value
        data:
          entity_id: input_number.termo_btc_switch_visual
          value: "0.0"
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.termo_btc_change_boost


  #### INVIO COMANDO HEATING - COOLING ####
  termo_btc_cmd_function:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: *topic_cmd
          payload: >-
            {% set funzione = states('sensor.termo_btc_funzione') %}
            {% if funzione == 'HEATING' %}COOLING
            {% elif funzione == 'COOLING' %}HEATING
            {% endif %}

          
  #########################
  #### SCRIPT PER CARD ####
  #########################

  #### AUMENTA SET POINT ####
  termo_btc_aumenta_temperatura:
    sequence:
      - condition: state
        entity_id: input_number.termo_btc_set_boost
        state: '0.0'
      - condition: state
        entity_id: input_boolean.termo_btc_change_boost
        state: 'off'
      - condition: state
        entity_id: binary_sensor.termo_btc_boost
        state: 'off'
      - service: input_number.increment
        data:
          entity_id: input_number.termo_btc_set_sp 
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.termo_btc_change_temp
          
          
  #### DIMINUISCI SET POINT ####
  termo_btc_diminuisci_temperatura:
    sequence:
      - condition: state
        entity_id: input_number.termo_btc_set_boost
        state: '0.0'
      - condition: state
        entity_id: input_boolean.termo_btc_change_boost
        state: 'off'
      - condition: state
        entity_id: binary_sensor.termo_btc_boost
        state: 'off'
      - service: input_number.decrement
        data:
          entity_id: input_number.termo_btc_set_sp 
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.termo_btc_change_temp


  #### INCREMENTA SWITCH VISUAL ####
  termo_btc_incrementa_switch_visual:
    sequence:
      - condition: state
        entity_id: input_number.termo_btc_set_boost
        state: '0.0'
      - condition: state
        entity_id: input_boolean.termo_btc_change_temp
        state: 'off'
      - condition: state
        entity_id: binary_sensor.termo_btc_boost
        state: 'off'
      - service: input_number.increment
        data:
          entity_id: input_number.termo_btc_switch_visual 


  #### INCREMENTA BOOST ####
  termo_btc_incrementa_boost:
    sequence:
      - service: input_number.increment
        data:
          entity_id: input_number.termo_btc_set_boost
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.termo_btc_change_boost