#!/bin/sh
if [ $# -eq 0 ] ; then
    echo 'Usage: $get_latest_release "creationix/nvm" --> v0.31.4'
    exit 0
fi

curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
grep '"tag_name":' |                                              # Get tag line
sed -E 's/.*"([^"]+)".*/\1/'                                      # Pluck JSON value