#!/bin/sh
if [[ $# -eq 0 ]] ; then
    echo 'Usage: hass_secret secret_key'
    exit 0
fi
cat /config/secrets.yaml | grep ^$1: | sed 's/ //g' | grep -Eo ':.*' | sed 's/://'
#grep ^$1: /config/secrets.yaml | sed 's/^[^:]*: //' | sed 's/ //g'